### ISSUE TITLE
Warn users if the playbook is executing on a server that isn't new

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#247]
There should be a step that pauses execution and displays a warning about possible consequences if the playbook is run against an existing server that has already been configured for other tasks. Checking the server's uptime is probably the easiest approach.

**Comment by lukeberry99** [comment]
Could there be false positives if the server had been restarted before running Streisand? Would checking when the file system was created be a better method? 

http://serverfault.com/questions/221377/how-to-determine-the-age-of-a-linux-system-since-installation

**Comment by aeibrahim** [comment]
What if instead the playbook was designed to be idempotent such that running it multiple times has no adverse affects?

**Comment by jlund** [comment]
This issue is specifically dealing with the scenario where someone tries to run Streisand on an existing *non-Streisand* server. I created it after someone emailed me who had attempted to run the playbook on their Apache-based webserver. Fortunately, they cancelled execution before it installed Nginx, removed Apache, and made a bunch of other changes to their personal webhost. 

The playbooks are designed to be idempotent and they can be run multiple times. I'm doing some cleanup in that area too.

**Comment by aeibrahim** [comment]
I misunderstood the problem here. In that case, you could check uptime but as @lukeberry99 mentioned, there could be false positives there. Uptime is stored in the `ansible_uptime_seconds` variable collected by setup. So something like this could work:

```
pre_tasks:
  - name: prompt the user if the server is not new 
    pause:
      prompt: "It looks like this server wasn't deployed using Streisand. Are you sure you wish to continue playbook execution? Press [Enter] to continue:"
    when: ansible_uptime_seconds|int < 30
```
This would run as a a pre-task before any role is executed.
