### ISSUE TITLE
Entire playbook should use multi-line YAML format

### ISSUE THREAD

**Issue by aeibrahim** [jlund/streisand#289]
Some parts of the playbook is using this format while other parts are using the multi-line YAML format:

```
- name: Update Monit configuration
  template: src=monitrc.j2
            dest=/etc/monit/monitrc
            owner=root
            group=root
            mode=700
  notify: Restart Monit
```

Can we convert it all to this format:
```
- name: Update Monit configuration
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: 700
  notify: Restart Monit
```
It makes it more legible and easier to understand and modify.
